restaurantes = [
    {"nome": "Nord Pizzaria", "tipo": "Pizza", "localidade": "centro", "preco_min": 20, "preco_max": 60},
    {"nome": "Point da Pizza", "tipo": "Pizza", "localidade": "centro", "preco_min": 20, "preco_max": 65},
    {"nome": "Pizzaria Oliver", "tipo": "Pizza", "localidade": "centro", "preco_min": 60, "preco_max": 100},
    {"nome": "Confratelli Pizaaria", "tipo": "Pizza", "localidade": "centro", "preco_min": 30, "preco_max": 80},
    {"nome": "Napoles Tratoria", "tipo": "Pizza", "localidade": "centro", "preco_min" :45 , "preco_max": 100},
    {"nome": "Tanakara", "tipo": "Japonês", "localidade": "centro", "preco_min": 60, "preco_max": 90},
    {"nome": "Kubo Sushi", "tipo": "Japonês", "localidade": "centro", "preco_min": 70, "preco_max": 95},
    {"nome": "YO! Japa", "tipo": "Japonês", "localidade": "centro", "preco_min": 50, "preco_max":80},
    {"nome": "Kami Sama", "tipo": "Japonês", "localidade": "centro", "preco_min": 65, "preco_max":100},
    {"nome": "Casa Grill/Sushi", "tipo": "Japonês", "localidade": "centro", "preco_min": 70, "preco_max":120},
    {"nome": "BB! Burguer", "tipo": "Haburguer", "localidade": "centro", "preco_min": 25, "preco_max":45},
    {"nome": "Argos Hamburgueria", "tipo": "Haburguer", "localidade": "centro", "preco_min": 30, "preco_max": 50},
    {"nome": "Burguer King", "tipo": "Haburguer", "localidade": "centro", "preco_min": 30, "preco_max": 60},
    {"nome": "No Limite", "tipo": "Haburguer", "localidade": "centro", "preco_min": 28, "preco_max": 50},
    {"nome": "Bobs Burguer", "tipo": "Haburguer", "localidade": "centro", "preco_min": 25, "preco_max": 55},
    {"nome": "Maminha de Ouro", "tipo": "Comida Brasileira", "localidade": "centro", "preco_min": 30, "preco_max":60},
    {"nome": "Varandão do Zé Carlos", "tipo": "Comida Brasileira", "localidade": "centro", "preco_min": 35, "preco_max": 65},
    {"nome": "Casa Grill", "tipo": "Comida Brasileira", "localidade": "centro", "preco_min": 70,"preco_max": 120},
    {"nome": "João João", "tipo": "Comida Brasileira", "localidade": "centro", "preco_min": 30,"preco_max": 55},
    {"nome": "Bom Gosto", "tipo": "Comida Brasileira", "localidade": "centro", "preco_min": 25,"preco_max": 50},
    {"nome": "Goulart Doceria", "tipo": "Sobremesa", "localidade": "centro", "preco_min": 10,"preco_max": 40},
    {"nome": "Doce Loucura", "tipo": "Sobremesa", "localidade": "centro", "preco_min": 12,"preco_max": 22},
    {"nome": "Sol & Neve Marica", "tipo": "Sobremesa", "localidade": "centro", "preco_min": 8,"preco_max": 40},
    {"nome": "Real Dreams Personalizados", "tipo": "Sobremesa", "localidade": "centro", "preco_min": 50,"preco_max": 80},
    {"nome": "Plano B", "tipo": "Sobremesa", "localidade": "centro", "preco_min": 6,"preco_max": 30},

    {"nome": "Pizzaria Oliver", "tipo": "Pizza", "localidade": "itaipuaçu", "preco_min": 60, "preco_max": 100},
    {"nome": "Domino's Pizza", "tipo": "Pizza", "localidade": "Itaipuaçu", "preco_min": 35, "preco_max": 80},
    {"nome": "Casa dos Sabores", "tipo": "Pizza", "localidade": "Itaipuaçu", "preco_min": 28, "preco_max": 45},
    {"nome": "Sprezzatura Itaipuaçu", "tipo": "Pizza", "localidade": "Itaipuaçu", "preco_min": 32, "preco_max": 48},
    {"nome": "AD Especiale Gourmet", "tipo": "Pizza", "localidade": "Itaipuaçu", "preco_min": 40, "preco_max": 60},
    {"nome": "Planeta Sushi", "tipo": "Japonês", "localidade": "Itaipuaçu", "preco_min": 70, "preco_max": 95},
    {"nome": "Sushi Rão", "tipo": "Japonês", "localidade": "Itaipuaçu", "preco_min": 65, "preco_max": 90},
    {"nome": "Japapi", "tipo": "Japonês", "localidade": "Itaipuaçu", "preco_min": 60, "preco_max": 85},
    {"nome": "Umai Sushi", "tipo": "Japonês", "localidade": "Itaipuaçu", "preco_min": 55, "preco_max": 80},
    {"nome": "Jomi Culinaria Oriental", "tipo": "Japonês", "localidade": "Itaipuaçu", "preco_min": 58, "preco_max": 90},
    {"nome": "Armazem 02 Burguer", "tipo": "Haburguer", "localidade": "Itaipuaçu", "preco_min": 30, "preco_max": 50},
    {"nome": "The Bigboy", "tipo": "Haburguer", "localidade": "Itaipuaçu", "preco_min": 35, "preco_max": 55},
    {"nome": "Elite Burguer's", "tipo": "Haburguer", "localidade": "Itaipuaçu", "preco_min": 28, "preco_max": 45},
    {"nome": "Insano Hamburgueria", "tipo": "Haburguer", "localidade": "Itaipuaçu", "preco_min": 40, "preco_max": 60},
    {"nome": "Raroo's Burguer", "tipo": "Haburguer", "localidade": "Itaipuaçu", "preco_min": 30, "preco_max": 50},
    {"nome": "Dona Jurema", "tipo": "Comida Brasileira", "localidade": "Itaipuaçu", "preco_min": 35, "preco_max": 60},
    {"nome": "Bem Servido Itaipuaçu", "tipo": "Comida Brasileira", "localidade": "Itaipuaçu", "preco_min": 40, "preco_max": 65},
    {"nome": "Tempero à Mineira", "tipo": "Comida Brasileira", "localidade": "Itaipuaçu", "preco_min": 35, "preco_max": 65},
    {"nome": "Hum Grill Itaipuaçu", "tipo": "Comida Brasileira", "localidade": "Itaipuaçu", "preco_min": 28, "preco_max": 50},
    {"nome": "Farofa Brasil", "tipo": "Comida Brasileira", "localidade": "Itaipuaçu", "preco_min": 40, "preco_max": 90},
    {"nome": "Brenda Doces Gourmet", "tipo": "Sobremesa", "localidade": "Itaipuaçu", "preco_min": 10, "preco_max": 20},
    {"nome": "Quasar Sorveteria", "tipo": "Sobremesa", "localidade": "Itaipuaçu", "preco_min": 12, "preco_max": 22},
    {"nome": "Mimos e Delicias", "tipo": "Sobremesa", "localidade": "Itaipuaçu", "preco_min": 8, "preco_max": 18},
    {"nome": "Casa dos Sabores", "tipo": "Sobremesa", "localidade": "Itaipuaçu", "preco_min": 12, "preco_max": 25},
    {"nome": "Sweet Life", "tipo": "Sobremesa", "localidade": "Itaipuaçu", "preco_min": 15, "preco_max": 28},

    {"nome": "Dominos's Pizza", "tipo": "Pizza", "localidade": "Ponta Negra", "preco_min": 35, "preco_max": 80},
    {"nome": "Pizzaria Famiglia Piazzola", "tipo": "Pizza", "localidade": "Ponta Negra", "preco_min": 35, "preco_max": 55},
    {"nome": "Páprika Pizzaria & Restaurante", "tipo": "Pizza", "localidade": "Ponta Negra", "preco_min": 28, "preco_max": 45},
    {"nome": "Fatia's Pizzaria", "tipo": "Pizza", "localidade": "Ponta Negra", "preco_min": 32, "preco_max": 48},
    {"nome": "Mazzano Restaurante", "tipo": "Pizza", "localidade": "Ponta Negra", "preco_min": 40, "preco_max": 60},
    {"nome": "Canal do Sushi", "tipo": "Japonês", "localidade": "Ponta Negra", "preco_min": 70, "preco_max": 95},
    {"nome": "OE Buguer", "tipo": "Haburguer", "localidade": "Ponta Negra", "preco_min": 30, "preco_max": 50},
    {"nome": "Argos Hamburgueria", "tipo": "Haburguer", "localidade": "Ponta Negra", "preco_min": 35, "preco_max": 55},
    {"nome": "Simburguer", "tipo": "Haburguer", "localidade": "Ponta Negra", "preco_min": 28, "preco_max": 45},
    {"nome": "Burgô Gastroburguer", "tipo": "Haburguer", "localidade": "Ponta Negra", "preco_min": 40, "preco_max": 60},
    {"nome": "Belego's Burger", "tipo": "Haburguer", "localidade": "Ponta Negra", "preco_min": 30, "preco_max": 50},
    {"nome": "Garota do Vale", "tipo": "Comida Brasileira", "localidade": "Ponta Negra", "preco_min": 35, "preco_max": 60},
    {"nome": "Seu Luiz Comida Caseira", "tipo": "Comida Brasileira", "localidade": "Ponta Negra", "preco_min": 40, "preco_max": 65},
    {"nome": "Bar da KeKé", "tipo": "Comida Brasileira", "localidade": "Ponta Negra", "preco_min": 35, "preco_max": 65},
    {"nome": "Restaurante dos 3 Food", "tipo": "Comida Brasileira", "localidade": "Ponta Negra", "preco_min": 28, "preco_max": 50},
    {"nome": "Casa do Esquerdinha", "tipo": "Comida Brasileira", "localidade": "Ponta Negra", "preco_min": 40, "preco_max": 90},
    {"nome": "M.B Cake", "tipo": "Sobremesa", "localidade": "Ponta Negra", "preco_min": 10, "preco_max": 20},
    {"nome": "Açaí Sabor Tropical", "tipo": "Sobremesa", "localidade": "Ponta Negra", "preco_min": 12, "preco_max": 22},
    {"nome": "Geladão Gourmet da Seia", "tipo": "Sobremesa", "localidade": "Ponta Negra", "preco_min": 8, "preco_max": 18},
    {"nome": "Lá na Doce", "tipo": "Sobremesa", "localidade": "Ponta Negra", "preco_min": 12, "preco_max": 25},
    {"nome": "Duarte Cakes", "tipo": "Sobremesa", "localidade": "Ponta Negra", "preco_min": 15, "preco_max": 28},

    {"nome": "Pizza Das Galaxyas", "tipo": "Pizza", "localidade": "Inoã", "preco_min": 30, "preco_max": 50},
    {"nome": "Trigo e Azeite", "tipo": "Pizza", "localidade": "Inoã", "preco_min": 35, "preco_max": 55},
    {"nome": "Pizzaria Brothers", "tipo": "Pizza", "localidade": "Inoã", "preco_min": 28, "preco_max": 45},
    {"nome": "Pizzaria Sabor da Italia", "tipo": "Pizza", "localidade": "Inoã", "preco_min": 32, "preco_max": 48},
    {"nome": "PH Pizzaria", "tipo": "Pizza", "localidade": "Inoã", "preco_min": 40, "preco_max": 60},
    {"nome": "Esquina do Yakissoba", "tipo": "Japonês", "localidade": "Inoã", "preco_min": 70, "preco_max": 95},
    {"nome": "Kamurai", "tipo": "Japonês", "localidade": "Inoã", "preco_min": 65, "preco_max": 90},
    {"nome": "Darumaki ", "tipo": "Japonês", "localidade": "Inoã", "preco_min": 60, "preco_max": 85},
    {"nome": "Gerê Burguer", "tipo": "Haburguer", "localidade": "Inoã", "preco_min": 30, "preco_max": 50},
    {"nome": "To Com Fome Maricá", "tipo": "Haburguer", "localidade": "Inoã", "preco_min": 35, "preco_max": 55},
    {"nome": "Krazo Hamburgueria", "tipo": "Haburguer", "localidade": "Inoã", "preco_min": 28, "preco_max": 45},
    {"nome": "Mec Burguer", "tipo": "Haburguer", "localidade": "Inoã", "preco_min": 40, "preco_max": 60},
    {"nome": "Jurassic Burguer", "tipo": "Haburguer", "localidade": "Inoã", "preco_min": 30, "preco_max": 50},
    {"nome": "Miguelito Grill", "tipo": "Comida Brasileira", "localidade": "Inoã", "preco_min": 35, "preco_max": 60},
    {"nome": "Imperio Costelaria", "tipo": "Comida Brasileira", "localidade": "Inoã", "preco_min": 40, "preco_max": 65},
    {"nome": "Estação + Sabor", "tipo": "Comida Brasileira", "localidade": "Inoã", "preco_min": 35, "preco_max": 65},
    {"nome": "Tempero da Sonia ", "tipo": "Comida Brasileira", "localidade": "Inoã", "preco_min": 28, "preco_max": 50},
    {"nome": "Esquina Brasileira", "tipo": "Comida Brasileira", "localidade": "Inoã", "preco_min": 40, "preco_max": 90},
    {"nome": "Elohim Confeitaria", "tipo": "Sobremesa", "localidade": "Inoã", "preco_min": 10, "preco_max": 20},
    {"nome": "MariaMaria ", "tipo": "Sobremesa", "localidade": "Inoã", "preco_min": 12, "preco_max": 22},
    {"nome": "Babi Confeitaria", "tipo": "Sobremesa", "localidade": "Inoã", "preco_min": 8, "preco_max": 18},
    {"nome": "Açai Bom Demais", "tipo": "Sobremesa", "localidade": "Inoã", "preco_min": 12, "preco_max": 25},
    {"nome": "Doceria Amor na Massa", "tipo": "Sobremesa", "localidade": "Inoã", "preco_min": 15, "preco_max": 28}
]